---
title: "BRCA_mutations_stratification"
output: html_document
date: "2024-05-09"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE)
library(tidyverse)
library(GenomicRanges)
library(reshape2)

SEED <- 4321
set.seed(SEED)

```

```{r}
source("/Users/ieo6983/Desktop/fragile_enhancer_clinical/utils/functions_genomics.R")

IN_FOLDER <- "/Users/ieo6983/Desktop/fragile_enhancer_clinical/"
OUT_FOLDER_DATA <- "/Users/ieo6983/Desktop/fragile_enhancer_clinical/results/ICGC/enhancers_SSMs_overlaps/data/"
OUT_FOLDER_PLOTS <- "/Users/ieo6983/Desktop/fragile_enhancer_clinical/results/ICGC/enhancers_SSMs_overlaps/plots/"

```


### Input files ###
```{r}
# SSMs
SSMs <- read_tsv("/Users/ieo6983/Desktop/fragile_enhancer_clinical/data/genomics/pre_processed_ICGC/from_gianluca.ssm.pcawg.coord.tsv")

SSMs$end <- SSMs$POS
SSMs <- SSMs %>% relocate(., end, .after = POS)
colnames(SSMs)[c(3, 4, 5)] <- c("seqnames", "start", "end")
SSMs$custom_mutation_id <- str_c(SSMs$Type, SSMs$seqnames, SSMs$start, SSMs$end, sep = "_")
SSMs_gr <- makeGRangesFromDataFrame(SSMs, keep.extra.columns = T)


# ALL enhancers: CtIP, GRHL
columns_names <- c("chrom", "start", "end", "cluster")
enh_ctip <- read_tsv(paste(IN_FOLDER, "data/functional_genomics/others/Cluster_CtIP_Enh_All.txt", sep=""), col_names = columns_names,
                     comment = "#")
enh_grhl <- read_tsv(paste(IN_FOLDER, "data/functional_genomics/others/Cluster_GRHL_Enh_All.txt", sep=""), col_names = columns_names, 
                     comment = "#")
enh_all <- list("CtIP" = enh_ctip, "GRHL" = enh_grhl)
# add summit & name
enh_all <- lapply(enh_all, function(df){
  df$summit <- df$end
  df$name <- str_c(df$chrom, df$summit, sep=":")
  return(df)})


# Putative enhancers: H3K27ac (no CtIP, GRHL, MRE11, self_overlaps)
put_enhancers <- read_tsv(paste(IN_FOLDER, "data/functional_genomics/others/PutativeEnhnacers_MCF10A_hg19.filtered_GRHL_CtIP_MRE11_self.tsv", sep=""))
colnames(put_enhancers)[1] <- "chrom" 
put_enhancers$summit <- put_enhancers$end


## HR-deficiency (BRCA somatic mutations) info - brcaT = BRCA-D  brcaF = BRCA-N
brca <- read_tsv("/Users/ieo6983/Desktop/enhancers_project/data/ICGC/icgc_data/metadata/simple_somatic_mutations.donors_brca_mutations.tsv")

label <- "brca_stratified"
brcaD <- brca[brca$brca_mut, ]$icgc_donor_id
brcaN <- brca[!brca$brca_mut, ]$icgc_donor_id


### 
WIN <- 3000
UNIT <- "bp"
MARKERS <- names(enh_all)

```


```{r}
input_variants <- SSMs
input_variants_gr <- SSMs_gr


enh_SSMs_tables <- vector("list", length(MARKERS))
names(enh_SSMs_tables) <- MARKERS

for(marker in MARKERS){
  mut <- "SSMs"
  
  # CtIP/GRHL enhancers
  marker_enh <- enh_all[[marker]] # select enhancer with 'marker'
  
  # Extend regions of 'win' from summit
  marker_enh$start <- marker_enh$summit - WIN
  marker_enh$end <- marker_enh$summit + WIN

  # Create GRanges objects 
  enh_gr <- makeGRangesFromDataFrame(marker_enh, keep.extra.columns = T)
  
  
  # Find mutations / enhancers overlaps 
  hits_obj_enh <- findOverlaps(query=enh_gr, subject=SSMs_gr)
  SSMs_sbj <- data.frame(SSMs_gr[subjectHits(hits_obj_enh)])
  colnames(SSMs_sbj)[1:5] <- paste(colnames(SSMs_sbj)[1:5], "sbj", sep = "_")
  enh_SSMs <- cbind(data.frame(enh_gr[queryHits(hits_obj_enh)]), SSMs_sbj) 
  
  enh_SSMs_tables[[marker]] <- enh_SSMs
}

```

```{r}
# Stratify SSMs based on patients with BRCA-mutations
brcaD_SSMs <- enh_SSMs_tables$CtIP[enh_SSMs_tables$CtIP$Sample %in% brcaD, ]
brcaN_SSMs <- enh_SSMs_tables$CtIP[enh_SSMs_tables$CtIP$Sample %in% brcaN, ]
ctip_SSMs_strat <- list("BRCA_D" = brcaD_SSMs, "BRCA_N" = brcaN_SSMs)

brcaD_SSMs <- enh_SSMs_tables$GRHL[enh_SSMs_tables$GRHL$Sample %in% brcaD, ]
brcaN_SSMs <- enh_SSMs_tables$GRHL[enh_SSMs_tables$GRHL$Sample %in% brcaN, ]
grhl2_SSMs_strat <- list("BRCA_D" = brcaD_SSMs, "BRCA_N" = brcaN_SSMs)

# Save stratified tables
for(name in names(ctip_SSMs_strat)){
  print(name)
  df <- ctip_SSMs_strat[[name]]
  
  df <- df %>% relocate(., summit, .before = start) 
  df$ssm_id <- paste(paste(df$seqnames_sbj, df$start_sbj-1, sep=":"), df$end_sbj,sep="-")
  df <- df %>% relocate(., ssm_id, .before = seqnames_sbj)
  #write_tsv(df, paste0(OUT_FOLDER_DATA, sprintf("Table_enh_SSMs_%s.all_overlaps.%s%s_WIN.%s.tsv", marker, WIN, UNIT, name)))
}

```


```{r}
## Stats
n_don <- table(brca$brca_mut)
names(n_don) <- c("BRCA_N", "BRCA_D")
print("Number of donors with and without BRCA mutations")
print(n_don)

print("Total number of mutations overlapping with GRHL2 enhancers")
print(paste0("BRCA-D: ", dim(brcaD_SSMs)[1]))
print(paste0("BRCA-N: ", dim(brcaN_SSMs)[1]))

for(name in names(grhl2_SSMs_strat)){
  df <- grhl2_SSMs_strat[[name]]  
  n_muts <- df %>% group_by(Sample) %>% 
    dplyr::summarise(n = length(unique(custom_mutation_id)))
  
  na_don <- n_don[[name]] - length(unique(df$Sample))
  avg_x_group <- round(mean(c(n_muts$n, rep(0, na_don))))
  print("Avg. number of SSMs x patient")
  print(paste0(name, ": ", avg_x_group))
}



```

```{r}
markers_ssms <- list("CtIP" = ctip_SSMs_strat, "GRHL" = grhl2_SSMs_strat)

markers_distances <- list(
  "CtIP" = data.frame("dist_enh" = NA, "group" = NA), 
  "GRHL" =data.frame("dist_enh" = NA, "group" = NA))

for(marker in names(markers_ssms)){
  print(marker)
    for(name in names(markers_ssms[[marker]])){
      print(name)
      dist_enh <- markers_ssms[[marker]][[name]]$start_sbj - markers_ssms[[marker]][[name]]$summit
      df <- data.frame("dist_enh" = dist_enh, "group" = rep(name, length(dist_enh)))
      markers_distances[[marker]] <- rbind(markers_distances[[marker]], df)
}
}


### Plot binned distributions
for(marker in MARKERS){
  title <- paste0("Density of distances from peak summit, BRCA stratified - ", marker)
  bw = 100
  
  p <- markers_distances[[marker]] %>% 
    ggplot(., aes(x = dist_enh, fill = group, color = group))+
    geom_density(alpha = 0.6, bw = bw)+
    labs(title = title)+
    theme_light()
  print(p)
}
    
```


```{r}
## Per cluster

clust_high_ctip <- c("CtIP_cluster_2_Enh", "CtIP_cluster_3_Enh", "CtIP_cluster_5_Enh")
clust_high_grhl <- c("GRHL_cluster_1_Enh", "GRHL_cluster_2_Enh", "GRHL_cluster_4_Enh")
clust_low_ctip <- c("CtIP_cluster_6.2_Enh", "CtIP_cluster_6.3_Enh", "CtIP_cluster_6.1_Enh", "CtIP_cluster_6.0")
clust_low_grhl <- c("GRHL_cluster_5.2_Enh", "GRHL_cluster_5.3_Enh", "GRHL_cluster_5.1_Enh", "GRHL_cluster_5.0")

clust_high <- list("CtIP" = clust_high_ctip, "GRHL" = clust_high_grhl)
clust_low <- list("CtIP" = clust_low_ctip, "GRHL" = clust_low_grhl)
clust_all <- list("high" = clust_high, "low" = clust_low)

markers_distances_clust <- list(
  "CtIP" = data.frame("dist_enh" = NA, "group" = NA, "cluster" = NA), 
  "GRHL" =data.frame("dist_enh" = NA, "group" = NA, "cluster" = NA))

for(marker in names(markers_ssms)){
  print(marker)
    for(name in names(markers_ssms[[marker]])){
      print(name)
      for(set in c("high", "low")){
        doi <- markers_ssms[[marker]][[name]] %>% filter(cluster %in% clust_all[[set]][[marker]])
        dist_enh <- doi$start_sbj - doi$summit   
        df <- data.frame("dist_enh" = dist_enh, "group" = rep(name, length(dist_enh)), "cluster" = set)
        markers_distances_clust[[marker]] <- rbind(markers_distances_clust[[marker]], df)
      }
}
}

for(marker in MARKERS){
  title <- paste0("Density of distances from peak summit, BRCA stratified - ", marker)
  bw = 100
  p <- markers_distances_clust[[marker]] %>% 
    ggplot(., aes(x = dist_enh, fill = interaction(group, cluster), color = interaction(group, cluster)))+
    geom_density(alpha = 0, bw = bw)+
    labs(title = title)+
    theme_light()
  print(p)
}


```

